from typing import Any

JsonObject = dict[str, Any]
AsonResult = JsonObject | list[JsonObject]

def encode(obj: JsonObject | list[JsonObject], schema: str) -> str: ...
def decode(text: str) -> AsonResult: ...
def encodePretty(obj: JsonObject | list[JsonObject], schema: str) -> str: ...
def encodeBinary(obj: JsonObject | list[JsonObject], schema: str) -> bytes: ...
def decodeBinary(data: bytes, schema: str) -> AsonResult: ...
